### ISSUE TITLE
Browsers

### ISSUE THREAD

**Issue by kosso** [Richienb/webm-to-mp4#3]
Can this work in a browser (ie not via Node) after processing it with something like `browserify`? 

Since Safari can now do `video|audio/mp4` natively using `MediaRecorder`, yet Chrome and FireFox can only do WebM, this module is the missing link to full compatibility for something I'd like to build.

But I'd rather it ran in the client/browser than the server/nodejs.

**Comment by Richienb** [comment]
Yes, there are no native dependencies so a bundler would be able to easily compile this package to run in a browser.

**Comment by rsvidevince** [comment]
Could you give us an example on how to turn a MediaRecorder blob array into an acceptable parameter for webmToMp4() call?

I've tried many things, always got the error:

```
Error: Conversion error
Invalid data found when processing input
```

**Comment by Richienb** [comment]
> Could you give us an example

[Here's how I did it](https://github.com/Richienb/capper/blob/b78ec03dcfc572f0309c3848cc268f476a6189ba/src/app.js#L454-L501)
