### ISSUE TITLE
Fuzzy quality

### ISSUE THREAD

**Issue by mikron123** [Richienb/webm-to-mp4#5]
I'm using this line
'-i video.webm -c:v mpeg4 -b:v 20000k -strict experimental output.mp4'

as you can see, I increased the quality, but the result image quality is still kind of fuzzy. Is there a way to use another compression? where can I find the list of all the possible parameters?

Thanks

**Comment by Richienb** [comment]
> where can I find the list of all the possible parameters?

https://ffmpeg.org/ffmpeg.html#Options

<blockquote><img src="favicon.ico" width="48" align="right"><div><strong><a href="https://ffmpeg.org/ffmpeg.html#Options">ffmpeg Documentation</a></strong></div></blockquote>

**Comment by mikron123** [comment]
@Richienb Thanks, though -c:v libx264 doesn't seem to work
I cannot seem to be able to upload the output video file (10 seconds long) to Instagram (tried via desktop Chrome)

**Comment by Richienb** [comment]
> -c:v libx264 doesn't seem to work

Tried `-c:v h264`?

**Comment by mikron123** [comment]
In both cases I get 

`Uncaught TypeError: Cannot read properties of undefined (reading 'data')
    at Worker.worker.onmessage`

Does it work for you?

**Comment by Richienb** [comment]
What code are you using?

**Comment by mikron123** [comment]
```js
function convertStreams(videoBlob, convertCB) {
      var aab;
      var buffersReady;
      var workerReady;
      var posted;

    var fileReader = new FileReader();
    fileReader.onload = function() {
        aab = this.result;
        postMessage();
    };

    fileReader.readAsArrayBuffer(videoBlob);

    if (!worker) {
        worker = processInWebWorker();
    }

    worker.onmessage = function(event) {

        var message = event.data;
        
        writeStatus(event.type);
        
        if (message.type == "ready") {
            writeStatus('<a href="'+ workerPath +'" download="ffmpeg-asm.js">ffmpeg-asm.js</a> file has been loaded.');

            workerReady = true;
            if (buffersReady)
                postMessage();
        } else if (message.type == "stdout") {
            writeStatus(message.data);
        } else if (message.type == "start") {
            writeStatus('<a href="'+ workerPath +'" download="ffmpeg-asm.js">ffmpeg-asm.js</a> file received ffmpeg command.');
        } else if (message.type == "done") {
            writeStatus(JSON.stringify(message));

            var result = message.data[0];
            writeStatus(JSON.stringify(result));

            var blob = new File([result.data], 'test.mp4', {
                type: 'video/mp4'
            });

            writeStatus(JSON.stringify(blob));

            //PostBlob(blob);
            downloadBlob(blob);
            // finished call CB
            convertCB();
        }
    };
    var postMessage = function() {
        posted = true;

        worker.postMessage({
            type: 'command',
            arguments: '-i video.webm -c:v h264 -b:v 20k -strict experimental output.mp4'.split(' '),
            files: [
                {
                    data: new Uint8Array(aab),
                    name: 'video.webm'
                }
            ]
        });
    };
}
```
message.data returns null.

CDN: `<script src="https://unpkg.com/@ffmpeg/ffmpeg@0.8.1/dist/ffmpeg.min.js"></script>`

Thanks

**Comment by Richienb** [comment]
If `message.data` returns null, you'll need to find out what `event.data` is and also check with the docs.

**Comment by mikron123** [comment]
Sorry, message.data doesn't return null, it's simply empty. message (event.data) has 2 more fields which are not data related.

**Comment by mikron123** [comment]
Do you have any working code with the h264 method?

**Comment by mikron123** [comment]
Ok, I just realized I'm getting an "unknown encoder: h264" message

**Comment by Richienb** [comment]
Try doing `-vcodec h264`

**Comment by mikron123** [comment]
Same message

**Comment by Richienb** [comment]
Must be `libx264` as you suggested earlier then

**Comment by Richienb** [comment]
Since you're using @ffmpeg/ffmpeg, I recommend asking around on https://github.com/ffmpegwasm/ffmpeg.wasm

**Comment by mikron123** [comment]
Thanks!
