### ISSUE TITLE
Converted Video Does Not Play in iOS Safari/Chrome

### ISSUE THREAD

**Issue by mojoalan** [Richienb/webm-to-mp4#7]
I am capturing short videos using MediaRecorder on various devices which need to be viewed on various devices. Hence the need to convert webm to mp4. In Chrome on Win10, I am recording video using a mimeType of "video/webm;codecs=h264". I convert the binary into base64 and post it to my Lambda/Nodejs (16.x) function. The Lambda function inspects the base64 and sees that it has "wemb" in the "data:" section. If so, it converts the base64 to a Buffer and then uses webm-to-mp4 to convert the Buffer to mp4, then my code converts the Buffer to base64 for storage. To view the video, I am using a Vuejs app that obtains the base64 video from a Lambda and then it uses an html5 video tag and dynamically sets the src attribute equal to the base64 string. All this works great if the video was recorded on an iOS device using the mimeType set to "video/mp4", but of course we have to use webm when recording the video on non-iOS devices. For the moment I am focusing on recording video using Chrome on Win10.

Here is my code that is doing the conversion using webm-to-mp4:

module.exports.webmToMp4 = async (strWebmDataUri) => {
    // require node's fs. https://nodejs.org/api/fs.html
    const { promises: fs } = require("fs");
    // require webm-to-mp4. https://www.npmjs.com/package/webm-to-mp4
    const webmToMp4 = require("webm-to-mp4");
    // strip intro bytes to obtain pure base64 string
    const strBase64 = strWebmDataUri.replace("data:video/webm;codecs=h264;base64,", "");
    // use fs Buffer to convert the base64 to a buffer
    const bufWebm = Buffer.from(strBase64, "base64");
    // use webToMp4 to transcode the buffer from webm to mp4
    const bufMp4 = Buffer.from(webmToMp4(bufWebm));
    // convert the buffer to base64 and append the intro bytes
    const strMp4DataUri = "data:video/mp4;codecs=h264;base64," + bufMp4.toString("base64");
    // return the (awesome) mp4 DataUri
    return strMp4DataUri;
}

I am preparing to do more analysis by using VLC to compare the codecs. I hope to compare between a webm, a webm converted to mp4, and a mp4 recorded on an iPhone. If you think that would be helpful just let me know and I will do that and post my findings. In the meantime, I am waiting on Pastebin to "moderate" my paste of a webm to mp4 video (base64 format). As soon as they approve my paste (I guess it looks fishy) I will post the link to it here.

Also, I am looking at this StackOverflow thread:

https://stackoverflow.com/questions/57812515/media-stream-recording-only-doesnt-work-on-iphone-safari-do-i-have-to-consider

One of the answers that seems to be quite authoritative says the following:

-------------------------------------------------------------------------------
There are 2 ways -

Solution #1 (NOT GUARANTEED) :

Try with VP8 codec like so: new Blob(recordedBlobs, {'video/webm;codecs=vp8'});
Solution #2 (GUARANTEED) :

Record with video/webm;codecs=h264, as MP4 and Webm supports h264 codec.

check for available containers here -> [video_codec_and_container](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs)

Now you just need to change the video container from WEBM to MP4. Which is way easy using tool such as [ffmpeg](https://ffmpeg.org/) - Note: copy the video codec, so that re-encoding will be avoided

ffmpeg -i INPUT.webm -codec:v copy OUTPUT.mp4
Recommendation: Convert videos to MP4 because WEBM has support for limited browsers.
-------------------------------------------------------------------------------

So, this is why I am trying to record using the codec set to h264. What do you think - can webm-to-mp4 accomplish what this is saying, where all it needs to do is change the video container from webm to mp4 without re-encoding? If so, then I think it would need to solve the audio codec issue as well, no? A pure webm shows the audio codec as Opus Audio (Opus), but a pure mp4 (no conversion, straight from an iPhone) shows the audio codec as MPEG AAC Audio (mp4a). So perhaps the end goal should be to remain in the H264 video codec, convert the audio from Opus to mp4a, and change the container to mp4. What do you think?

**Comment by mojoalan** [comment]
Ahh, I see that I can upload files right here without bothering with Pastebin. Great! Here are three videos along with their base64 version for each...

(removed)

**Comment by Richienb** [comment]
The difference is the audio codec:

- The first file uses AAC LC
- The second and third file use Opus

**Comment by mojoalan** [comment]
Yes, that is exactly what I was saying. The input file uses Opus and webm-to-mp4 is not converting the audio to AAC LC. If it would do that, then the converted videos would work on iOS/Safari/Chrome. So the question is, could webm-to-mp4 be enhanced to also convert audio codec from Opus to AAC LC?

**Comment by Richienb** [comment]
The module has only ever changed the container format for the video. See #6

**Comment by mojoalan** [comment]
Good news, I got ffmpeg wasm working in Lambda/node and all is well. It does the same thing but also does the audio conversion. That’s what was missing, and now the converted mp4 videos play in Safari/chrome on iOS, with the src attribute being set to the DataUri base64 string. Thanks a ton for your help.
